import { requireAdmin } from "./auth.js";

export default function handler(req, res) {
  if (!requireAdmin(req, res)) return;
  if (req.method !== "GET") return res.status(405).send("Method not allowed");

  res.setHeader("Content-Type", "text/html; charset=utf-8");
  return res.status(200).send(String.raw`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Events Admin | Wilco Welding</title><style>
:root{--ink:#172031;--muted:#667085;--line:#d8dee8;--canvas:#f4f6f9;--accent:#d97706;--accent-dark:#a95005;--success:#087443;--danger:#bd2424}*{box-sizing:border-box}body{margin:0;color:var(--ink);background:var(--canvas);font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}.topbar{background:#111827;color:#fff;border-bottom:4px solid var(--accent)}.topbar-inner,main{width:min(100% - 32px,900px);margin:auto}.topbar-inner{padding:20px 0}.topbar h1{margin:0;font-size:1.2rem}.topbar p{margin:3px 0 0;color:#d1d5db;font-size:.88rem}main{margin-top:32px;margin-bottom:56px}.card{background:#fff;border:1px solid var(--line);border-radius:16px;padding:clamp(20px,4vw,34px);box-shadow:0 12px 30px rgba(16,24,40,.06)}h2{margin:0 0 7px}p{line-height:1.55;color:var(--muted)}.event-list{display:grid;gap:12px;margin-top:24px}.event-row{display:grid;grid-template-columns:minmax(0,1fr) 210px auto;gap:10px;align-items:end;padding:14px;border:1px solid var(--line);border-radius:10px;background:#fbfcfe}.field{display:flex;flex-direction:column;gap:6px}label{font-size:.82rem;font-weight:750}input{width:100%;padding:10px 11px;border:1px solid #b9c2d0;border-radius:8px;font:inherit;color:var(--ink)}input:focus{outline:0;border-color:var(--accent);box-shadow:0 0 0 3px rgba(217,119,6,.15)}button{appearance:none;border:0;border-radius:8px;padding:10px 14px;font:inherit;font-weight:750;cursor:pointer}.primary{background:var(--accent);color:#fff}.primary:hover{background:var(--accent-dark)}.secondary{background:#edf1f6;color:#263244}.remove{background:#feecec;color:#9c1c1c}.actions{display:flex;flex-wrap:wrap;gap:12px;align-items:center;margin-top:24px;padding-top:22px;border-top:1px solid var(--line)}#status{margin:0;min-height:1.4em;font-size:.9rem}#status[data-kind="success"]{color:var(--success)}#status[data-kind="error"]{color:var(--danger)}@media(max-width:650px){.event-row{grid-template-columns:1fr}.event-row .remove{width:100%}.actions{align-items:stretch;flex-direction:column}.actions button{width:100%}}
</style></head><body><header class="topbar"><div class="topbar-inner"><h1>Wilco Welding Events Admin</h1><p>Add, update, or remove Upcoming Events on the website.</p></div></header><main><section class="card"><h2>Upcoming Events</h2><p>These events appear on the Home page and the Upcoming Events page. They are managed here only—Google Calendar is no longer connected.</p><div class="event-list" id="eventList"></div><div class="actions"><button class="secondary" id="add" type="button">Add another event</button><button class="primary" id="save" type="button">Save events</button><p id="status" aria-live="polite">Loading events…</p></div></section></main><script>
const list=document.getElementById("eventList"),status=document.getElementById("status");
const setStatus=(message,kind)=>{status.textContent=message;status.dataset.kind=kind||""};
function addRow(title="",date=""){const row=document.createElement("div");row.className="event-row";const titleField=document.createElement("div");titleField.className="field";const titleLabel=document.createElement("label");titleLabel.textContent="Event name";const titleInput=document.createElement("input");titleInput.className="event-title";titleInput.value=title;titleInput.placeholder="Example: Skills Competition";titleField.append(titleLabel,titleInput);const dateField=document.createElement("div");dateField.className="field";const dateLabel=document.createElement("label");dateLabel.textContent="Date or date range";const dateInput=document.createElement("input");dateInput.className="event-date";dateInput.value=date;dateInput.placeholder="Example: June 7, 2026";dateField.append(dateLabel,dateInput);const remove=document.createElement("button");remove.type="button";remove.className="remove";remove.textContent="Remove";remove.onclick=()=>row.remove();row.append(titleField,dateField,remove);list.appendChild(row)}
async function load(){try{const response=await fetch("/content.json",{cache:"no-store"});if(!response.ok)throw new Error("Could not load events.");const content=await response.json();const events=Array.isArray(content.events)?content.events:[];events.forEach(event=>addRow(event[0]||"",event[1]||""));if(!events.length)addRow();setStatus("Current events loaded.","success")}catch(error){setStatus("Error: "+error.message,"error")}}
document.getElementById("add").onclick=()=>addRow();
document.getElementById("save").onclick=async()=>{const button=document.getElementById("save");const events=[...document.querySelectorAll(".event-row")].map(row=>[row.querySelector(".event-title").value.trim(),row.querySelector(".event-date").value.trim()]).filter(event=>event[0]||event[1]);button.disabled=true;setStatus("Saving events…");try{const response=await fetch("/api/update-content",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({events})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||"Could not save events.");setStatus("Saved! The website has been updated.","success")}catch(error){setStatus("Save error: "+error.message,"error")}finally{button.disabled=false}};
load();
</script></body></html>`);
}