import { requireAdmin } from "./auth.js";

export default function handler(req,res) {
  if (!requireAdmin(req,res)) return;
  res.setHeader("Content-Type","text/html; charset=utf-8");
  res.status(200).send(String.raw`<!doctype html><meta name="viewport" content="width=device-width"><title>Edit Homepage Hero</title>
<style>body{margin:0;background:#f4f6f9;font:16px system-ui;color:#172031}.bar{background:#111827;color:#fff;padding:20px}.wrap{max-width:720px;margin:32px auto;padding:0 18px}.card{background:#fff;border:1px solid #d8dee8;border-radius:14px;padding:28px}label{display:block;font-weight:700;margin:16px 0 7px}input,textarea{box-sizing:border-box;width:100%;padding:11px;border:1px solid #b9c2d0;border-radius:8px;font:inherit}textarea{min-height:110px}button{margin-top:18px;padding:11px 16px;border:0;border-radius:8px;font-weight:800;cursor:pointer;background:#d97706;color:#fff}.secondary{background:#e8edf3;color:#172031;margin-left:8px}#status{margin-left:12px}</style>
<div class="bar"><b>Wilco Welding Admin</b> · Edit homepage hero</div><main class="wrap"><a href="/admin">← Back to blog editor</a><section class="card"><h1>Homepage Hero</h1><label>Small heading<input id="eyebrow"></label><label>Main heading<input id="title"></label><label>Description<textarea id="description"></textarea></label><label>Button text<input id="button"></label><label>Background image URL<input id="image"></label><label>Upload new image<input id="file" type="file" accept="image/*"></label><button id="upload" class="secondary">Upload image</button><button id="save">Save hero</button><span id="status"></span></section></main>
<script type="module">import{upload}from"https://esm.sh/@vercel/blob@2.0.0/client";const keys=["eyebrow","title","description","button","image"],g=id=>document.getElementById(id),s=t=>g("status").textContent=t;let hero={};try{hero=(await (await fetch("/content.json")).json()).hero||{};keys.forEach(k=>g(k).value=hero[k]||"");s("Loaded")}catch(e){s(e.message)}g("upload").onclick=async()=>{const f=g("file").files[0];if(!f)return s("Choose an image.");s("Uploading…");try{const b=await upload("uploads/"+f.name,f,{access:"public",handleUploadUrl:"/api/upload"});g("image").value=b.url;s("Uploaded — now save.")}catch(e){s("Upload error: "+e.message)}};g("save").onclick=async()=>{keys.forEach(k=>hero[k]=g(k).value.trim());s("Saving…");const r=await fetch("/api/update-content",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({hero})});s(r.ok?"Saved!":"Save failed.")}</script>`);
}