import { requireAdmin } from "./auth.js";

export default function handler(req, res) {
  if (!requireAdmin(req, res)) return;
  if (req.method !== "GET") return res.status(405).send("Method not allowed");

  res.setHeader("Content-Type", "text/html; charset=utf-8");
  return res.status(200).send(String.raw`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Partners Admin | Wilco Welding</title><style>
:root{--ink:#172031;--muted:#667085;--line:#d8dee8;--canvas:#f4f6f9;--accent:#d97706;--accent-dark:#a95005;--success:#087443;--danger:#bd2424}*{box-sizing:border-box}body{margin:0;color:var(--ink);background:var(--canvas);font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}.topbar{background:#111827;color:#fff;border-bottom:4px solid var(--accent)}.topbar-inner,main{width:min(100% - 32px,960px);margin:auto}.topbar-inner{padding:20px 0}.topbar h1{margin:0;font-size:1.2rem}.topbar p{margin:3px 0 0;color:#d1d5db;font-size:.88rem}main{margin-top:32px;margin-bottom:56px}.card{background:#fff;border:1px solid var(--line);border-radius:16px;padding:clamp(20px,4vw,34px);box-shadow:0 12px 30px rgba(16,24,40,.06)}h2{margin:0 0 7px}p{line-height:1.55;color:var(--muted)}.partner-list{display:grid;gap:14px;margin-top:24px}.partner-row{display:grid;grid-template-columns:190px minmax(0,1fr) auto;gap:18px;align-items:center;padding:16px;border:1px solid var(--line);border-radius:11px;background:#fbfcfe}.preview{width:190px;height:135px;border:1px solid var(--line);background:#fff;border-radius:7px;display:flex;align-items:center;justify-content:center;overflow:hidden;color:var(--muted);font-size:.75rem}.preview img{max-width:100%;max-height:100%;object-fit:contain}.fields{display:grid;grid-template-columns:1fr 1fr;gap:10px}.field{display:flex;flex-direction:column;gap:6px}label{font-size:.81rem;font-weight:750}input{width:100%;padding:10px 11px;border:1px solid #b9c2d0;border-radius:8px;font:inherit;color:var(--ink)}input:focus{outline:0;border-color:var(--accent);box-shadow:0 0 0 3px rgba(217,119,6,.15)}input[type="file"]{padding:7px}.upload-row{display:flex;gap:8px;align-items:end}.upload-row input{min-width:0}.upload{background:#edf1f6;color:#263244}.remove{background:#feecec;color:#9c1c1c}.actions{display:flex;flex-wrap:wrap;gap:12px;align-items:center;margin-top:24px;padding-top:22px;border-top:1px solid var(--line)}button{appearance:none;border:0;border-radius:8px;padding:10px 14px;font:inherit;font-weight:750;cursor:pointer}.primary{background:var(--accent);color:#fff}.primary:hover{background:var(--accent-dark)}.secondary{background:#edf1f6;color:#263244}#status{margin:0;min-height:1.4em;font-size:.9rem}#status[data-kind="success"]{color:var(--success)}#status[data-kind="error"]{color:var(--danger)}@media(max-width:720px){.partner-row{grid-template-columns:1fr}.preview{width:100%;height:180px}.fields{grid-template-columns:1fr}.upload-row{align-items:stretch;flex-direction:column}.actions{align-items:stretch;flex-direction:column}.actions button,.remove{width:100%}}
</style></head><body><header class="topbar"><div class="topbar-inner"><h1>Wilco Welding Partners Admin</h1><p>Add, update, or remove employer and partner organizations.</p></div></header><main><section class="card"><h2>Employers &amp; Partners</h2><p>Partner names and logos appear on the Home page and the Employers &amp; Partners page. You can keep up to 30 organizations.</p><div class="partner-list" id="partnerList"></div><div class="actions"><button class="secondary" id="add" type="button">Add another partner</button><button class="primary" id="save" type="button">Save partners</button><p id="status" aria-live="polite">Loading partners…</p></div></section></main><script type="module">
import { upload } from "https://esm.sh/@vercel/blob@2.0.0/client";
const list=document.getElementById("partnerList"),status=document.getElementById("status");
const setStatus=(message,kind)=>{status.textContent=message;status.dataset.kind=kind||""};
function addRow(partner={}){const row=document.createElement("div");row.className="partner-row";const preview=document.createElement("div");preview.className="preview";const refresh=()=>{preview.replaceChildren();if(image.value){const photo=document.createElement("img");photo.src=image.value;photo.alt=name.value||"Partner logo";preview.appendChild(photo)}else{preview.textContent="No logo yet"}};const fields=document.createElement("div");fields.className="fields";const nameField=document.createElement("div");nameField.className="field";const nameLabel=document.createElement("label");nameLabel.textContent="Organization name";const name=document.createElement("input");name.className="partner-name";name.value=partner.name||"";name.placeholder="Example: Local 597";nameField.append(nameLabel,name);const imageField=document.createElement("div");imageField.className="field";const imageLabel=document.createElement("label");imageLabel.textContent="Logo web address";const image=document.createElement("input");image.className="partner-image";image.value=partner.image||"";image.placeholder="Filled after upload";image.oninput=refresh;imageField.append(imageLabel,image);const uploadField=document.createElement("div");uploadField.className="field";const uploadLabel=document.createElement("label");uploadLabel.textContent="Upload logo";const uploadRow=document.createElement("div");uploadRow.className="upload-row";const file=document.createElement("input");file.type="file";file.accept="image/jpeg,image/png,image/webp,image/gif";const uploadButton=document.createElement("button");uploadButton.type="button";uploadButton.className="upload";uploadButton.textContent="Upload";uploadButton.onclick=async()=>{const selected=file.files[0];if(!selected)return setStatus("Choose a logo before uploading.","error");if(selected.size>10*1024*1024)return setStatus("That logo is larger than 10 MB.","error");uploadButton.disabled=true;setStatus("Uploading logo…");try{const blob=await upload("uploads/"+selected.name,selected,{access:"public",handleUploadUrl:"/api/upload"});image.value=blob.url;refresh();setStatus("Logo uploaded. Save partners to publish it.","success")}catch(error){setStatus("Upload error: "+error.message,"error")}finally{uploadButton.disabled=false}};uploadRow.append(file,uploadButton);uploadField.append(uploadLabel,uploadRow);fields.append(nameField,imageField,uploadField);const remove=document.createElement("button");remove.type="button";remove.className="remove";remove.textContent="Remove";remove.onclick=()=>row.remove();row.append(preview,fields,remove);list.appendChild(row);refresh()}
async function load(){try{const response=await fetch("/content.json",{cache:"no-store"});if(!response.ok)throw new Error("Could not load partners.");const content=await response.json();const partners=Array.isArray(content.partners)?content.partners:[];partners.forEach(addRow);if(!partners.length)addRow();setStatus("Current partners loaded.","success")}catch(error){setStatus("Error: "+error.message,"error")}}
document.getElementById("add").onclick=()=>addRow();
document.getElementById("save").onclick=async()=>{const button=document.getElementById("save");const partners=[...document.querySelectorAll(".partner-row")].map(row=>({name:row.querySelector(".partner-name").value.trim(),image:row.querySelector(".partner-image").value.trim()})).filter(partner=>partner.name||partner.image);button.disabled=true;setStatus("Saving partners…");try{const response=await fetch("/api/update-content",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({partners})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||"Could not save partners.");setStatus("Saved! Your partner pages have been updated.","success")}catch(error){setStatus("Save error: "+error.message,"error")}finally{button.disabled=false}};
load();
</script></body></html>`);
}